name: Node.js CI

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/Food-App-Backend
            git stash
            git pull https://Geethanjali12:${{ secrets.TOKEN }}@github.com/Geethanjali12/Food-App-Backend
            cd /root/Food-App-Backend
            npm install -f
            pm2 restart cdn